# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

**NumpyNotebook: 25 single star, 29 double star, 33 triple star**

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config

1.22.4


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
val=np.zeros(10)
print(val)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
n=[10,3,45,8,7]
array = np.array(n)
memory_size = array.nbytes
print(f"Memory size array: {memory_size} bytes")

Memory size array: 40 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np

print(np.add.__doc__)



#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
val=np.zeros(10)
val[4]=1
print(val)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector=np.arange(10,50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
n=[10,3,45,8,7]
n=n[::-1]
print(n)

[7, 8, 45, 3, 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
values=  np.arange(9)
matrix=values.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
# Create the array
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
array = np.random.random((3,3,3))
print(array)

[[[0.78431715 0.73243408 0.01694548]
  [0.65057858 0.23825449 0.51587997]
  [0.06598459 0.17066462 0.36168839]]

 [[0.70986972 0.12565278 0.42009279]
  [0.81228012 0.8279607  0.70951644]
  [0.63080854 0.90477478 0.15611276]]

 [[0.19571135 0.83629894 0.5976271 ]
  [0.8159197  0.80476499 0.71324786]
  [0.34295248 0.2416944  0.9455321 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
array = np.random.random((10,10))
print("10x10 array", array)


minVal= np.min(array)
print("minimum value", minVal)
maxVal= np.max(array)
print("maximum value", maxVal)

10x10 array [[0.55425047 0.32487526 0.432258   0.61321824 0.67694561 0.10729803
  0.06684968 0.022383   0.11031538 0.7964152 ]
 [0.25931552 0.57501287 0.90325559 0.07880506 0.68801691 0.40756299
  0.34921146 0.4649772  0.8044742  0.62760516]
 [0.37896087 0.70600941 0.43911167 0.65202474 0.85146254 0.76563004
  0.10173999 0.19041095 0.17294206 0.37262362]
 [0.48106138 0.20824942 0.47816842 0.23612544 0.10973926 0.20183211
  0.78835733 0.58262975 0.54779786 0.93145603]
 [0.4535521  0.16583617 0.89352679 0.82573427 0.10304012 0.69141304
  0.66922228 0.71527673 0.97172819 0.21062285]
 [0.83994562 0.45312412 0.93920616 0.37671302 0.9992768  0.42643863
  0.31981622 0.61956778 0.2731937  0.53511286]
 [0.67187892 0.05524139 0.12210595 0.35344848 0.84303862 0.93128524
  0.01693265 0.21734314 0.54118168 0.85991434]
 [0.37481643 0.52542647 0.09913762 0.05699869 0.51820811 0.41013444
  0.50083942 0.1113882  0.19604051 0.75777938]
 [0.11699717 0.17817922 0.59971126 0.78169822 0.30600007 0.04398413


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
vector = np.random.random(30)
mean = vector.mean()
print(mean)

0.44403919735052216


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array= np.ones((5,5))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
# Using fancy indexing
array[:, [0, -1]] = 0
array[[0, -1], :] = 0
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
arr = np.random.rand(6, 7, 8)

# Find the index (x, y, z) of the 100th element
flat_index = 100
index_xyz = np.unravel_index(flat_index, arr.shape)

print("Index (x, y, z) of the 100th element:", index_xyz)

Index (x, y, z) of the 100th element: (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
checkerboard_tile = np.array([[0, 1], [1, 0]])

# Use tile function to repeat the checkerboard tile to create an 8x8 checkerboard matrix
checkerboard = np.tile(checkerboard_tile, (4, 4))

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
array = np.random.random((5,5))
array = (array - np.mean (array)) / (np.std (array))
print(array)

[[-0.36067425  0.08529497  1.71127499 -1.23663576  0.39875278]
 [ 0.76431333  0.64726883 -0.91590691  0.45041447 -0.56081073]
 [ 0.84064804  0.74307659  1.12889409 -1.2035614  -0.5116492 ]
 [-1.65844256  1.19861713  0.0762718  -1.73857874  0.30712842]
 [-0.56218031  1.67295729 -0.2833737   0.65339273 -1.64649188]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
rgba_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
color = np.array((255, 128, 64, 255), dtype=rgba_dtype)

print("Custom dtype for RGBA colors:" , color)


Custom dtype for RGBA colors: (255, 128, 64, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.rand(5, 3)

# Create the 3x2 matrix
B = np.random.rand(3, 2)

# Multiply the matrices
result = np.dot(A, B)

print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[0.78287262 0.69363238]
 [0.61082896 0.5577511 ]
 [0.47699218 0.10865121]
 [0.05869243 0.15343206]
 [0.45386198 0.25723405]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# Create a 1D array
arr = np.array([1, 4, 6, 7, 2, 9, 8, 5, 3])
mask = (arr > 3) & (arr < 8)

# Negate the elements that satisfy the mask
arr[mask] = -arr[mask]

print("Updated array:", arr)

Updated array: [ 1 -4 -6 -7  2  9  8 -5  3]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
array = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(array)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.rand(5) * 10
print(Z - Z%1)
print([int(num) for num in Z])
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[4. 6. 7. 0. 2.]
[4, 6, 7, 0, 2]
[4. 6. 7. 0. 2.]
[4 6 7 0 2]
[4. 6. 7. 0. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
Z = np.linspace(0,1,11, endpoint=False)
print(Z)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
random_vector = np.random.random(10)

# Sort the random vector in ascending order
random_vector.sort()

print(random_vector)

[0.00335002 0.03241012 0.1588119  0.36832998 0.39911257 0.42721505
 0.42997802 0.75520269 0.83356131 0.90407152]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
array = np.arange(5)
np.add.reduce(array )


10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
# Create two random arrays A and B
A = np.random.rand(7)
B = np.random.rand(7)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

print("Arrays A and B are equal:", are_equal)

Arrays A and B are equal: False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Convert the array to a tuple
immutable_tuple = tuple(arr)

# Attempt to modify the tuple (will raise an error)
try:
    immutable_tuple[0] = 10
except TypeError as e:
    print("Error:", e)

Error: 'tuple' object does not support item assignment


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


[1.1235258  0.32965731 0.79098319 0.58717639 1.02729919 0.7505415
 0.80642042 1.26367192 0.70747876 0.4489957 ]
[0.68944194 1.11484395 0.02951618 1.01038749 0.36871768 0.35131166
 0.99566818 0.66394036 1.33292874 0.23156245]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
array = np.random.random(10)
array[array.argmax()] = 0
print(array)

[0.21559969 0.57566386 0.70291608 0.55744264 0.         0.06169993
 0.18299921 0.02016186 0.30842058 0.53343065]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
array = np.zeros((5,5), [('x',float),('y',float)])
array['x'], array['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Print all the values of the array using a for loop
for value in arr:
    print(value)

1
2
3
4
5


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

74


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
position_dtype = [('x', float), ('y', float)]
color_dtype = [('r', int), ('g', int), ('b', int)]

data = np.array([((1.5, 2.0), (255, 0, 0)),
                 ((3.0, 4.5), (0, 255, 0)),
                 ((0.5, 1.0), (0, 0, 255))], dtype=[('position', position_dtype), ('color', color_dtype)])

print(data)

[((1.5, 2. ), (255,   0,   0)) ((3. , 4.5), (  0, 255,   0))
 ((0.5, 1. ), (  0,   0, 255))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.14560232 0.2035086  0.26364421 0.8607678  0.08590193
  0.92613407 0.64226178 0.57111288 0.07694161]
 [0.14560232 0.         0.34911011 0.12380954 0.80721818 0.09249074
  0.90931715 0.53410228 0.58589373 0.21851268]
 [0.2035086  0.34911011 0.         0.4649645  0.96859957 0.27726298
  0.98667675 0.81368145 0.61182568 0.13622808]
 [0.26364421 0.12380954 0.4649645  0.         0.83141283 0.2154961
  0.96207617 0.50716346 0.66747158 0.33927292]
 [0.8607678  0.80721818 0.96859957 0.83141283 0.         0.78520954
  0.24253645 0.40342753 0.41739049 0.8684445 ]
 [0.08590193 0.09249074 0.27726298 0.2154961  0.78520954 0.
  0.86426065 0.55636625 0.52232715 0.14123833]
 [0.92613407 0.90931715 0.98667675 0.96207617 0.24253645 0.86426065
  0.         0.61466093 0.37579703 0.91344569]
 [0.64226178 0.53410228 0.81368145 0.50716346 0.40342753 0.55636625
  0.61466093 0.         0.52739329 0.68349105]
 [0.57111288 0.58589373 0.61182568 0.66747158 0.41739049 0.52232715
  0.37579703 0.527393

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
# Create a float (32 bits) array
float_array = np.array([1.5, 2.7, 3.9, 4.2], dtype=np.float32)

# Convert the float array to an integer (32 bits) array in place
int_array = float_array.view(dtype=np.int32)

print("Float Array:", float_array)
print("Integer Array:", int_array)

Float Array: [1.5 2.7 3.9 4.2]
Integer Array: [1069547520 1076677837 1081711002 1082549862]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.38725268 -0.0256166  -0.07891005  0.36987603 -0.47627789 -0.16311819
  -0.20760998  0.4736622  -0.12156317 -0.15769505]
 [ 0.25045454 -0.03555852 -0.18368258 -0.38259445 -0.22378607  0.16763191
  -0.18791159  0.47711071 -0.26403155  0.38236759]
 [-0.49532214 -0.07353678  0.07500661 -0.1466229  -0.32871047  0.47174036
   0.20500555 -0.36698362  0.3658645   0.29355888]
 [ 0.3431595  -0.14962324  0.06906569 -0.19221295 -0.18569733 -0.12486321
   0.36382878  0.11994597 -0.11632905 -0.12727417]
 [-0.23127601 -0.06224219  0.22147342  0.00694896 -0.07331523  0.32658345
  -0.08741607 -0.22186954  0.27892097 -0.15780775]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 1 8]
 [5 7 6]
 [3 5 1]]
[[6 1 8]
 [3 5 1]
 [5 7 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5792431070109041


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:

array1 = np.array([[1, 2, 3]])
array2 = np.array([[4],
                   [5],
                   [6]])

# Ensure both arrays have shapes (3,)
array1 = np.squeeze(array1)
array2 = np.squeeze(array2)

# Compute the sum using an iterator
sum_result = np.zeros_like(array1)
for i in range(len(array1)):
    sum_result[i] = array1[i] + array2[i]

print("Array 1:", array1)
print("Array 2:", array2)
print("Sum Result:", sum_result)


Array 1: [1 2 3]
Array 2: [4 5 6]
Sum Result: [5 7 9]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 2. 4. 7. 5. 3. 1. 3. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[50 60 50 52]
 [57 49 64 58]
 [63 40 49 39]]
[[50 60 50 52]
 [57 49 64 58]
 [63 40 49 39]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.32747894 0.47121863 0.43972877 0.51589652 0.58513007 0.5003605
 0.44050873 0.53657248 0.5041759  0.41259673]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute the dot product of A and B
dot_product = np.dot(A, B)  # or dot_product = A @ B

# Get the diagonal elements of the dot product matrix
diagonal = np.diag(dot_product)

print("Dot product matrix:")
print(dot_product)
print("Diagonal of the dot product matrix:", diagonal)

Dot product matrix:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Diagonal of the dot product matrix: [30 69 90]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])

# Build a vector with 3 zeros between each value
interleaved_zeros = np.repeat(0, 3 * len(Z))
interleaved_zeros[::3] = Z
print("Vector with interleaved zeros:", interleaved_zeros)


Vector with interleaved zeros: [1 0 0 2 0 0 3 0 0 4 0 0 5 0 0]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
array[0], array[1] = array[1], array[0]

print("Array after swapping rows:")
print(array)

Array after swapping rows:
[[4 5 6]
 [4 5 6]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 34) ( 2, 50) (10, 16) (10, 67) (16, 67) (17, 83) (17, 92) (31, 34)
 (31, 92) (32, 36) (32, 90) (34, 41) (34, 43) (34, 50) (34, 71) (34, 74)
 (34, 92) (36, 59) (36, 62) (36, 90) (41, 43) (50, 56) (50, 84) (53, 66)
 (53, 69) (56, 84) (59, 62) (66, 69) (71, 74) (83, 92)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
# Example one-dimensional array
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create the two-dimensional array
rows = 3
cols = len(Z) - rows + 1

two_dim_array = np.vstack([Z[i:i+rows] for i in range(cols)])

print("Original one-dimensional array:", Z)
print("Two-dimensional array:")
print(two_dim_array)

Original one-dimensional array: [1 2 3 4 5 6 7 8 9]
Two-dimensional array:
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.48812291,  0.49664892,  0.47061532,  0.69336903,  0.29245184,
        0.22160449,  0.17004283,  0.79532935,  0.53411606, -0.80488399,
        0.4257532 , -0.64206798, -0.87227347, -0.28658992,  0.65847174,
        0.54358289,  0.8530522 ,  0.1983807 , -0.41521637,  0.40832011,
       -0.21744159, -0.90383032,  0.53963934, -0.25483108, -0.15662365,
        0.93504328, -0.95481392, -0.74677748,  0.04350109, -0.86745212,
       -0.60135296,  0.59311198, -0.64958374, -0.94019968,  0.58568017,
        0.5398825 ,  0.82752417,  0.10296008, -0.31178879,  0.42458566,
        0.32218561,  0.73837715, -0.26073254, -0.14437008, -0.9662563 ,
       -0.12876229,  0.97648965, -0.59461685, -0.43839193, -0.22069553,
       -0.87489183, -0.60647189,  0.98712754,  0.47840043, -0.9076421 ,
       -0.03856854,  0.01015919, -0.55050278,  0.52378664, -0.24391806,
        0.68416263, -0.12642163,  0.33561437, -0.52728838,  0.12794189,
       -0.85209722,  0.16832492, -0.10843987,  0.78474975,  0.01

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:

def extract_subpart(arr, center, shape, fill_value=0):
    # Get the dimensions of the input array
    arr_shape = np.array(arr.shape)

    # Calculate the lower and upper bounds for each dimension
    lower_bounds = np.maximum(center - np.floor_divide(shape, 2), 0)
    upper_bounds = np.minimum(lower_bounds + shape, arr_shape)

    # Create an array of indices for each dimension
    indices = [np.arange(lower, upper) for lower, upper in zip(lower_bounds, upper_bounds)]

    mesh_indices = np.meshgrid(*indices, indexing='ij')

    # Stack the indices to form an array of coordinates
    coordinates = np.stack(mesh_indices, axis=-1)

    # Use the coordinates to extract the subpart from the original array
    subpart = arr[tuple(coordinates.T)]

    # Create an array of the desired shape filled with the fill value
    result = np.full(shape, fill_value)

    offsets = np.maximum(np.floor_divide(shape, 2) - center + lower_bounds, 0)

    region = [slice(offset, offset + sub_size) for offset, sub_size in zip(offsets, subpart.shape)]

    result[region] = subpart

    return result

arr = np.arange(25).reshape(5, 5)
center = (2, 2)
shape = (3, 3)
subpart = extract_subpart(arr, center, shape, fill_value=-1)

print("Original Array:")
print(arr)
print("\nExtracted Subpart:")
print(subpart)


Original Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Extracted Subpart:
[[ 6 11 16]
 [ 7 12 17]
 [ 8 13 18]]


<ipython-input-11-8c17707975ab>:27: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result[region] = subpart


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [ ]:
arr = np.array([1, 2, 3, 2, 4, 2, 5, 5, 5])

# Get unique elements and their counts
unique_elements, counts = np.unique(arr, return_counts=True)

# Find the index of the maximum count
most_frequent_index = np.argmax(counts)

# The most frequent value
most_frequent_value = unique_elements[most_frequent_index]

print("Array:", arr)
print("Most frequent value:", most_frequent_value)

Array: [1 2 3 2 4 2 5 5 5]
Most frequent value: 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[3 0 2]
   [3 2 4]
   [4 4 1]]

  [[0 2 3]
   [2 4 1]
   [4 1 2]]

  [[2 3 0]
   [4 1 3]
   [1 2 1]]

  [[3 0 1]
   [1 3 3]
   [2 1 3]]

  [[0 1 2]
   [3 3 0]
   [1 3 2]]

  [[1 2 2]
   [3 0 3]
   [3 2 0]]

  [[2 2 2]
   [0 3 1]
   [2 0 0]]

  [[2 2 1]
   [3 1 1]
   [0 0 2]]]


 [[[3 2 4]
   [4 4 1]
   [3 2 2]]

  [[2 4 1]
   [4 1 2]
   [2 2 2]]

  [[4 1 3]
   [1 2 1]
   [2 2 4]]

  [[1 3 3]
   [2 1 3]
   [2 4 3]]

  [[3 3 0]
   [1 3 2]
   [4 3 3]]

  [[3 0 3]
   [3 2 0]
   [3 3 1]]

  [[0 3 1]
   [2 0 0]
   [3 1 2]]

  [[3 1 1]
   [0 0 2]
   [1 2 3]]]


 [[[4 4 1]
   [3 2 2]
   [0 2 1]]

  [[4 1 2]
   [2 2 2]
   [2 1 0]]

  [[1 2 1]
   [2 2 4]
   [1 0 3]]

  [[2 1 3]
   [2 4 3]
   [0 3 3]]

  [[1 3 2]
   [4 3 3]
   [3 3 0]]

  [[3 2 0]
   [3 3 1]
   [3 0 1]]

  [[2 0 0]
   [3 1 2]
   [0 1 2]]

  [[0 0 2]
   [1 2 3]
   [1 2 3]]]


 [[[3 2 2]
   [0 2 1]
   [1 1 0]]

  [[2 2 2]
   [2 1 0]
   [1 0 0]]

  [[2 2 4]
   [1 0 3]
   [0 0 0]]

  [[2 4 3]
   [0 3 3]
   [0 0 3]]

  [[4 3 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  7  9  8 18]
 [ 7  7 14  5 12]
 [ 9 14  2 42  7]
 [ 8  5 42  8  6]
 [18 12  7  6  4]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
A = np.array([[1, 2, 3],
              [2, 3, 4],
              [5, 6, 7]
            ])

B = np.array([[1, 2],
              [3, 4]])

# Check if rows of A contain elements of each row of B regardless of order
rows_containing_elements_of_B = np.all(np.isin(A, B), axis=1)

# Filter the rows of A that meet the condition
filtered_rows_of_A = A[rows_containing_elements_of_B]

print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nRows of A containing elements of each row of B regardless of order:")
print(filtered_rows_of_A)

Array A:
[[1 2 3]
 [2 3 4]
 [5 6 7]]

Array B:
[[1 2]
 [3 4]]

Rows of A containing elements of each row of B regardless of order:
[[1 2 3]
 [2 3 4]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


1.66 s ± 609 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
185 ms ± 4.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
176 ms ± 18.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 3 2]
 [3 4 1]
 [0 0 1]
 [4 3 4]
 [2 3 2]
 [4 1 4]
 [0 1 1]
 [4 0 0]
 [1 1 0]
 [3 4 4]]
[[1 3 2]
 [3 4 1]
 [0 0 1]
 [4 3 4]
 [2 3 2]
 [4 1 4]
 [0 1 1]
 [4 0 0]
 [1 1 0]
 [3 4 4]]
[[1 3 2]
 [3 4 1]
 [0 0 1]
 [4 3 4]
 [2 3 2]
 [4 1 4]
 [0 1 1]
 [4 0 0]
 [1 1 0]
 [3 4 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.06342841, 0.04799958, 0.00117833, 0.06818382, 0.03243891,
        0.01597841, 0.03576607, 0.02997456, 0.08005323, 0.03251853],
       [0.37731017, 0.28553023, 0.0070094 , 0.40559823, 0.19296606,
        0.09504918, 0.21275801, 0.17830664, 0.47620459, 0.1934397 ],
       [0.42538204, 0.32190871, 0.00790245, 0.45727419, 0.21755124,
        0.10715909, 0.23986482, 0.20102411, 0.53687627, 0.21808522],
       [0.45470368, 0.34409793, 0.00844717, 0.48879416, 0.23254707,
        0.11454558, 0.25639873, 0.21488073, 0.57388323, 0.23311787],
       [0.3433382 , 0.25982188, 0.0063783 , 0.36907928, 0.17559192,
        0.08649121, 0.19360186, 0.1622524 , 0.43332844, 0.17602292],
       [0.26374357, 0.19958848, 0.00489964, 0.28351721, 0.1348852 ,
        0.06644032, 0.14871997, 0.12463812, 0.33287176, 0.13521628],
       [0.27308026, 0.20665404, 0.00507309, 0.2935539 , 0.13966022,
        0.06879235, 0.15398475, 0.12905039, 0.34465563, 0.14000302],
       [0.44062115, 0.33344094, 0.0081855

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
X = np.array([1, 2, 4, 6, 8])
Y = np.array([2, 4, 7, 3, 1])

# Number of equidistant samples
num_samples = 10

# Sample the X and Y vectors using equidistant samples
X_sampled = np.linspace(X[0], X[-1], num_samples)
Y_sampled = np.interp(X_sampled, X, Y)

# Print the sampled coordinates
print("Sampled X coordinates:", X_sampled)
print("Sampled Y coordinates:", Y_sampled)

Sampled X coordinates: [1.         1.77777778 2.55555556 3.33333333 4.11111111 4.88888889
 5.66666667 6.44444444 7.22222222 8.        ]
Sampled Y coordinates: [2.         3.55555556 4.83333333 6.         6.77777778 5.22222222
 3.66666667 2.55555556 1.77777778 1.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.14683024  0.1946093 ]
